version: '3.8'

services:
  backend:
    image: tyzer/backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    image: tyzer/frontend
    build:
      context: ./scan-ticket-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
