# Étape 1 : Construire le frontend avec Node.js
FROM node:20 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers package.json et package-lock.json pour optimiser le cache
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Construire l'application
RUN npm run build

# Étape 2 : Utiliser une image Nginx pour servir les fichiers statiques
FROM nginx:latest

# Copier les fichiers construits dans le répertoire Nginx par défaut
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer directement le port 8080
EXPOSE 8080

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
