# Utiliser une image Node.js pour construire le frontend
FROM node:18 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install -g npm@latest
RUN npm install qrcode --save

# Copier tout le code source du frontend
#COPY scan-ticket-app/ ./
COPY . ./

# Construire l'application
RUN npm run build

# Utiliser une image Nginx pour servir les fichiers statiques
FROM nginx:latest

# Copier les fichiers construits dans le répertoire Nginx par défaut
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
