# Étape 1 : Utiliser une image Node.js stable
FROM node:20

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier uniquement la partie backend (Strapi)
COPY package.json package-lock.json ./
COPY config ./config
COPY src ./src
COPY database ./database
COPY public ./public

# Vérifie les fichiers copiés
RUN ls -la

# Étape 4 : Installer les dépendances
RUN npm install --production

# Étape 5 : Définir les variables d’environnement (si nécessaire)
ENV NODE_ENV=production

# Étape 6 : Exposer le port utilisé par Strapi
EXPOSE 1337

# Étape 7 : Lancer Strapi en mode production
CMD ["npm", "start"]
