# Étape 1 : Utiliser une image Node.js stable
FROM node:20

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /backend

# Étape 3 : Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install -g npm@latest && npm install

# Étape 5 : Copier tous les fichiers du projet dans le conteneur
COPY . .

# Étape 6 : Copier le fichier .env (assurez-vous qu'il existe à la racine de votre projet)
COPY ./src/.env /backend/.env


# Étape 7 : Assurer que les répertoires nécessaires existent et ont les bonnes permissions
RUN mkdir -p .cache .tmp && chmod -R 775 .cache .tmp

# Étape 8 : Exposer le port utilisé par Strapi
EXPOSE 1337

# Étape 9 : Démarrer l'application Strapi
CMD ["npm", "run", "develop"]
