# Étape 1 : Utiliser une image Node.js stable
FROM node:20

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /src

# Étape 3 : Copier uniquement les fichiers package.json pour installer les dépendances
COPY package*.json ./

# Vérifie les fichiers copiés
RUN ls -la

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier tout le code du projet dans le conteneur
COPY src/. .

# Étape 6 : Définir les variables d’environnement (si nécessaire)
ENV NODE_ENV=production

# Étape 7 : Exposer le port utilisé par Strapi
EXPOSE 1337

# Étape 8 : Lancer Strapi en mode production
CMD ["npm", "start"]
